[package]
name = "pt-wavefront"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bytemuck = { workspace = true }
log = { workspace = true }
wgpu = { workspace = true }
gpu-mem = { workspace = true }
render-core = { workspace = true }
