[package]
name = "render-3d"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
half = { workspace = true }
bytemuck = { workspace = true }
glam = { workspace = true }
image = { workspace = true }
log = { workspace = true }
wgpu = { workspace = true }
squarebob-core = { workspace = true }
render-core = { workspace = true }
render-shared = { workspace = true }
color-pipeline = { workspace = true }
pt-core = { workspace = true }
pt-megakernel = { workspace = true }
pt-mats = { workspace = true }
pt-material = { workspace = true }
treemap = { workspace = true }
