[package]
name = "treemap"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
squarebob-core = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }

[dependencies.bytemuck]
workspace = true
optional = true

[dependencies.wgpu]
workspace = true
optional = true

[dependencies.render-core]
workspace = true

[features]
default = ["cpu"]
cpu = []
wgpu = ["dep:wgpu", "dep:bytemuck"]
cuda = []
