[package]
name = "pt-megakernel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bytemuck = { workspace = true }
half = { workspace = true }
log = { workspace = true }
wgpu = { workspace = true }
glam = { workspace = true }
pt-core = { workspace = true }
bvh-gpu = { workspace = true }
pt-wavefront = { workspace = true }
render-core = { workspace = true }
